### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by guozheng** [yahoo/ycb#17]
Is it possible to improve the README a bit to include the bundle specifications and possibly some examples? I know the tests covers some of the examples, but it would be really nice to cover these in the documentation.

**Comment by mysterycommand** [comment]
+1

The [public YCB Wiki page](https://github.com/yahoo/ycb/wiki) refers me to [Mojito's use of YCB](https://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_using_contexts.html). As someone who is new to YCB, this is very confusing. YCB is it's own thing, used by Mojito … can't it have it's own documentation? How old is that Mojito stuff anyway? Also, could that documentation please assume that it's audience is new to YCB?

**Comment by redonkulus** [comment]
@mysterycommand fyi i did this over a year ago but it has stagnated: https://github.com/yahoo/ycb/pull/27

**Comment by redonkulus** [comment]
I've just updated my PR to incorporate @caridy feedback.

**Comment by redonkulus** [comment]
#27 was merged, so there is at least an example on the read me now. I agree that a spec would be good too. Some of it could be taken from https://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_using_contexts.html

**Comment by caridy** [comment]
good, thanks for merging the example @redonkulus.

@mysterycommand yes, it is its own thing, very popular within yahoo, not so much outside yahoo, it is suppose to solve a complex problem that is hard to describe jejeje. hope that the example from @redonkulus will make people curious about it, and I hope that eventually, someone will send a PR with some good docs :), I'm open to review it :)
