### ISSUE TITLE
ycb doesn't do replacement for empty values

### ISSUE THREAD

**Issue by pranavparikh** [yahoo/ycb#28]
Here, if we've "filterUrl" as "", ycb doesn't replace it.

e.g
1)
[{"dimensions":[{"environment":{"development":{"dev":null,"test":null},"production":{"int":null,"stage":null,"prod":null}}}]},{"settings":["master"],"name":"highlander_client","config":{"baseUrl":"http://finance.yahoo.com","filterUrl":""},"dataprovider":{"Test YHOO Original 1":{"group":"smoke","params":{"page":"$$config.baseUrl$$$$config.filterUrl$$","test":"test.js"}}}}]

after ycb replacement translates to 

{"name":"highlander_client","config":{"baseUrl":"http://finance.yahoo.com","filterUrl":""},"dataprovider":{"Test YHOO Original 1":{"group":"smoke","params":{"page":"$$config.baseUrl$$$$config.filterUrl$$","test":"test.js"}}}}

2)
In case of non-empty values, replacement works good

[{"dimensions":[{"environment":{"development":{"dev":null,"test":null},"production":{"int":null,"stage":null,"prod":null}}}]},{"settings":["master"],"name":"highlander_client","config":{"baseUrl":"http://finance.yahoo.com","filterUrl":"/q?s=YHOO"},"dataprovider":{"Test YHOO Original 1":{"group":"smoke","params":{"page":"$$config.baseUrl$$$$config.filterUrl$$","test":"test.js"}}}}]

after ycb replacement translates to 

{"name":"highlander_client","config":{"baseUrl":"http://finance.yahoo.com","filterUrl":"/q?s=YHOO"},"dataprovider":{"Test YHOO Original 1":{"group":"smoke","params":{"page":"http://finance.yahoo.com/q?s=YHOO","test":"test.js"}}}}

**Comment by redonkulus** [comment]
Fixed bt #29
